server {
    listen 8082;
    server_name _;

    root /usr/share/nginx/html;
    index page/index.html;

    location /page/ {
        try_files $uri /page/index.html;
    }

    location /page/api/ {
        resolver           127.0.0.11 valid=30s ipv6=off;
        set $upstream      page-api:8001;
        rewrite            ^/page/api/(.*) /$1 break;
        proxy_pass         http://$upstream;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   Cf-Access-Authenticated-User-Email $http_cf_access_authenticated_user_email;
        proxy_buffering    off;
        proxy_cache        off;
        proxy_read_timeout 120s;
    }
}
